Feature/PostgreSql Script
dsccommunity/PostgreSqlDsc pull request #5
Opened 2020-10-27 13:54 UTC by themitchk

# Pull Request
[PostgreSqlDsc] Added PostgreSqlScript resource

## Pull Request (PR) description
Allows execution of T-SQL scripts against a PostgreSql Database

### Added
- Added PostgreSqlScript resource
  - Run T-SQL Scripts against Postgres

## Task list

- [x] The PR represents a single logical change. i.e. Cosmetic updates should go in different PRs.
- [x] Added an entry under the Unreleased section of in the CHANGELOG.md as per [format](https://keepachangelog.com/en/1.0.0/).
- [x] Local clean build passes without issue or fail tests (`build.ps1 -ResolveDependency`).
- [x] Resource documentation added/updated in README.md.
- [x] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [x] Comment-based help added/updated.
- [x] Localization strings added/updated in all localization files as appropriate.
- [x] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

2020-10-27 17:47 UTC, rchristman89 reviewed
> Reviewed 2 of 7 files at r1, 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/postgresqldsc/5)* status: 3 of 8 files reviewed, 4 unresolved discussions (waiting on @chtoone, @jcwalker, @jeffotterpohl, @regedit32, and @themitchk)

___
*[README.md, line 39 at r2](https://reviewable.io/reviews/dsccommunity/postgresqldsc/5#-MKeYBWP8fgJbTBwoCcM:-MKeYBWP8fgJbTBwoCcN:b-3ykpzz) ([raw file](https://github.com/dsccommunity/postgresqldsc/blob/688e5fa5b0d1a43ed6504b3ebcf50c24792c3f8a/README.md#L39)):*
> ```Markdown
> | ---- | ---- | ---- | ---- | ---- |
> | DatabaseName | Key | String | Specifies the name of the _PostgreSQL_ database. | |
> | SetFilePath | Key | String | Path to the T-SQL file that will perform _Set_ action | |
> ```

I would add a period to unify all the descriptions.
___
*[README.md, line 42 at r2](https://reviewable.io/reviews/dsccommunity/postgresqldsc/5#-MKeY8OJCFGlO-uxGQK8:-MKeY8OJCFGlO-uxGQK9:bifvd0w) ([raw file](https://github.com/dsccommunity/postgresqldsc/blob/688e5fa5b0d1a43ed6504b3ebcf50c24792c3f8a/README.md#L42)):*
> ```Markdown
> | GetFilePath | Key | String | Path to the T-SQL file that will perform _Get_ action | |
> | SetFilePath | Key | String | Path to the T-SQL file that will perform _Test_ action | |
> | Credential | Required | PsCredential | The credentials to authenticate with, using _Postgres Authentication_. | |
> ```

Credential is not required but write. 
___
*[source/DSCResources/DSC_PostgreSqlScript/DSC_PostgreSqlScript.psm1, line 25 at r2](https://reviewable.io/reviews/dsccommunity/postgresqldsc/5#-MKeYUQ97nFdA764I5Vf:-MKeYUQ97nFdA764I5Vg:bb64e1a) ([raw file](https://github.com/dsccommunity/postgresqldsc/blob/688e5fa5b0d1a43ed6504b3ebcf50c24792c3f8a/source/DSCResources/DSC_PostgreSqlScript/DSC_PostgreSqlScript.psm1#L25)):*
> ```PowerShell
>         The credentials to authenticate with, using PostgreSQL Authentication.
>     .PARAMETER PsqlLocation
>         Location of the psql executable.  Defaults to "C:\Program Files\PostgreSQL\12\bin\psql.exe"
> ```

Missing period.
___
*[source/DSCResources/DSC_PostgreSqlScript/DSC_PostgreSqlScript.psm1, line 54 at r2](https://reviewable.io/reviews/dsccommunity/postgresqldsc/5#-MKebEqW-Bh0uG4oHiba:-MKebBX2DwvisAJBXkLq:b3exi1q) ([raw file](https://github.com/dsccommunity/postgresqldsc/blob/688e5fa5b0d1a43ed6504b3ebcf50c24792c3f8a/source/DSCResources/DSC_PostgreSqlScript/DSC_PostgreSqlScript.psm1#L54)):*
> ```
>         [System.Management.Automation.Credential()]
> ```
This allows you to pass in a username as a string and have an interactive prompt for the password, which I’ll demonstrate later in the post. I tested this out and it does not work in DSC. This can be removed.


<!-- Sent from Reviewable.io -->

2020-10-27 18:27 UTC, rchristman89 requested changes
> Reviewed 2 of 7 files at r1, 2 of 3 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/postgresqldsc/5)* status: all files reviewed, 8 unresolved discussions (waiting on @chtoone, @jcwalker, @jeffotterpohl, @regedit32, and @themitchk)

___
*[source/DSCResources/DSC_PostgreSqlScript/DSC_PostgreSqlScript.psm1, line 152 at r3](https://reviewable.io/reviews/dsccommunity/postgresqldsc/5#-MKfC1mI2Z1aeg8eaPha:-MKfC1mI2Z1aeg8eaPhb:b-k9j9hy) ([raw file](https://github.com/dsccommunity/postgresqldsc/blob/acadc69eedcc26b051f12737c063fff344ad3caf/source/DSCResources/DSC_PostgreSqlScript/DSC_PostgreSqlScript.psm1#L152)):*
> ```PowerShell
>         $previousErrorActionPreference = $ErrorActionPreference
>         $ErrorActionPreference = "Stop"
>         $DbExists = $false;
> ```

I believe acronyms of two letters should be capitalized for camelCase. 
Same with $db below
___
*[source/DSCResources/DSC_PostgreSqlScript/DSC_PostgreSqlScript.psm1, line 153 at r3](https://reviewable.io/reviews/dsccommunity/postgresqldsc/5#-MKfCmGE6S93bPs_PvlC:-MKfCmGE6S93bPs_PvlD:b-e5rd3n) ([raw file](https://github.com/dsccommunity/postgresqldsc/blob/acadc69eedcc26b051f12737c063fff344ad3caf/source/DSCResources/DSC_PostgreSqlScript/DSC_PostgreSqlScript.psm1#L153)):*
> ```PowerShell
>         $ErrorActionPreference = "Stop"
>         $DbExists = $false;
>         $DbList = Invoke-Command -ScriptBlock {& $PsqlLocation -lqt 2>&1}
> ```

I would add a verbose statement before this saying it is "Listing databases" or something similar. It helps when debugging. It may be nice to put the command being ran in the statement.
___
*[source/DSCResources/DSC_PostgreSqlScript/DSC_PostgreSqlScript.psm1, line 166 at r3](https://reviewable.io/reviews/dsccommunity/postgresqldsc/5#-MKfCwSn7twAn30NCMi5:-MKfCwSn7twAn30NCMi6:bmomaxo) ([raw file](https://github.com/dsccommunity/postgresqldsc/blob/acadc69eedcc26b051f12737c063fff344ad3caf/source/DSCResources/DSC_PostgreSqlScript/DSC_PostgreSqlScript.psm1#L166)):*
> ```PowerShell
>         if ($DbExists -eq $false -and $CreateDatabase)
>         {
>             Invoke-Command -ScriptBlock {
> ```

I would add a verbose statement before this saying it is "Creating databases" or something similar. It helps when debugging. It may be nice to put the command being ran in the statement.
___
*[source/DSCResources/DSC_PostgreSqlScript/DSC_PostgreSqlScript.psm1, line 170 at r3](https://reviewable.io/reviews/dsccommunity/postgresqldsc/5#-MKfD-_MALiEChmlmbcv:-MKfD-_MALiEChmlmbcw:bzbbkw) ([raw file](https://github.com/dsccommunity/postgresqldsc/blob/acadc69eedcc26b051f12737c063fff344ad3caf/source/DSCResources/DSC_PostgreSqlScript/DSC_PostgreSqlScript.psm1#L170)):*
> ```PowerShell
>             }
>         }
>         Invoke-Command -ScriptBlock {
> ```

I would move the verbose statement from above to here, 
```
Write-Verbose -Message ($script:localizedData.ExecutingSetScript -f $SetFilePath,$DatabaseName)
```'
It may be nice to put the command being ran in the statement.
```



<!-- Sent from Reviewable.io -->

2020-10-27 18:29 UTC, jcwalker reviewed
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/postgresqldsc/5)* status: all files reviewed, 14 unresolved discussions (waiting on @chtoone, @jeffotterpohl, @regedit32, and @themitchk)

___
*[source/PostgreSqlDsc.psd1, line 85 at r3](https://reviewable.io/reviews/dsccommunity/postgresqldsc/5#-MKfGSZwAilqmevcTZQk:-MKfGSZx9X12M7Ss0Nxx:b-5hjmf8) ([raw file](https://github.com/dsccommunity/postgresqldsc/blob/acadc69eedcc26b051f12737c063fff344ad3caf/source/PostgreSqlDsc.psd1#L85)):*
> ```
> ,
> ```
The comma isn't needed since the new resource is on a newline.
___
*[source/DSCResources/DSC_PostgreSqlScript/DSC_PostgreSqlScript.psm1, line 151 at r3](https://reviewable.io/reviews/dsccommunity/postgresqldsc/5#-MKfHSFY7irHkyEG7g5l:-MKfHSFY7irHkyEG7g5m:b-uer16j) ([raw file](https://github.com/dsccommunity/postgresqldsc/blob/acadc69eedcc26b051f12737c063fff344ad3caf/source/DSCResources/DSC_PostgreSqlScript/DSC_PostgreSqlScript.psm1#L151)):*
> ```
>         $previousErrorActionPreference = $ErrorActionPreference
>         $ErrorActionPreference = "Stop"
> ```
Why are we doing this vs adding a '-ErrorAction Stop' at the end the cmdlets?
___
*[source/DSCResources/DSC_PostgreSqlScript/DSC_PostgreSqlScript.psm1, line 169 at r3](https://reviewable.io/reviews/dsccommunity/postgresqldsc/5#-MKfGy9dEusGO5FhWOlF:-MKfGy9dEusGO5FhWOlG:b7mzf5t) ([raw file](https://github.com/dsccommunity/postgresqldsc/blob/acadc69eedcc26b051f12737c063fff344ad3caf/source/DSCResources/DSC_PostgreSqlScript/DSC_PostgreSqlScript.psm1#L169)):*
> ```PowerShell
>                 & $PsqlLocation -d 'postgres' -c "CREATE DATABASE $DatabaseName"
>             }
>         }
> ```

Style guidelines suggest a newline after a closing brace.
https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#two-newlines-after-closing-brace
___
*[source/DSCResources/DSC_PostgreSqlScript/DSC_PostgreSqlScript.psm1, line 198 at r3](https://reviewable.io/reviews/dsccommunity/postgresqldsc/5#-MKfHjED2dI1UEmnwCcj:-MKfHjED2dI1UEmnwCck:b-91t3p9) ([raw file](https://github.com/dsccommunity/postgresqldsc/blob/acadc69eedcc26b051f12737c063fff344ad3caf/source/DSCResources/DSC_PostgreSqlScript/DSC_PostgreSqlScript.psm1#L198)):*
> ```
> `
> ```
Did we want to use backticks ( `GetResult`) or single quotes ('GetResult') to surround GetResult
___
*[source/DSCResources/DSC_PostgreSqlScript/DSC_PostgreSqlScript.schema.mof, line 6 at r3](https://reviewable.io/reviews/dsccommunity/postgresqldsc/5#-MKfJOEk9yKHXdh1xG8b:-MKfJOEk9yKHXdh1xG8c:b-lxmt6v) ([raw file](https://github.com/dsccommunity/postgresqldsc/blob/acadc69eedcc26b051f12737c063fff344ad3caf/source/DSCResources/DSC_PostgreSqlScript/DSC_PostgreSqlScript.schema.mof#L6)):*
> ```
>     [Key, Description("Specifies the name of the _PostgreSQL_ database.")] String DatabaseName;
>     [Key, Description("Path to the T-SQL file that will perform _Set_ action.")] String SetFilePath;
>     [Key, Description("Path to the T-SQL file that will perform _Get_ action. Any values returned by the T-SQL queries will also be returned when calling _Get_ (for example by using the cmdlet `Get-DscConfiguration`) through the `'GetResult'` property.")] String GetFilePath;
> ```

Are the backticks needed?
___
*[tests/Unit/DSCResources/DSC_PostgreSqlScript.tests.ps1, line 107 at r3](https://reviewable.io/reviews/dsccommunity/postgresqldsc/5#-MKfJA4l6ZcvoiQfxhIJ:-MKfJA4m0qbVmVlrBYe6:b-gautc2) ([raw file](https://github.com/dsccommunity/postgresqldsc/blob/acadc69eedcc26b051f12737c063fff344ad3caf/tests/Unit/DSCResources/DSC_PostgreSqlScript.tests.ps1#L107)):*
> ```PowerShell
>                         Set-TargetResource @NoCreateParams
>                         Assert-VerifiableMock
>                         Assert-MockCalled Invoke-Command -Exactly -Times 2 -Scope It
> ```

We should use the parameter name -CommandName on all the Assert-MockCalled(s)


<!-- Sent from Reviewable.io -->

2020-10-27 19:19 UTC, themitchk reviewed
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/postgresqldsc/5)* status: 3 of 8 files reviewed, 14 unresolved discussions (waiting on @chtoone, @jcwalker, @jeffotterpohl, @rchristman89, and @regedit32)

___
*[README.md, line 39 at r2](https://reviewable.io/reviews/dsccommunity/postgresqldsc/5#-MKeYBWP8fgJbTBwoCcM:-MKfTF0J2Eq-aVuuMYaU:b-896fix) ([raw file](https://github.com/dsccommunity/postgresqldsc/blob/688e5fa5b0d1a43ed6504b3ebcf50c24792c3f8a/README.md#L39)):*
<details><summary><i>Previously, rchristman89 (Ryan Christman) wrote…</i></summary><blockquote>

I would add a period to unify all the descriptions.
</blockquote></details>

Done.
___
*[README.md, line 42 at r2](https://reviewable.io/reviews/dsccommunity/postgresqldsc/5#-MKeY8OJCFGlO-uxGQK8:-MKfTGq4CFU3Gtw15HQo:b-896fix) ([raw file](https://github.com/dsccommunity/postgresqldsc/blob/688e5fa5b0d1a43ed6504b3ebcf50c24792c3f8a/README.md#L42)):*
<details><summary><i>Previously, rchristman89 (Ryan Christman) wrote…</i></summary><blockquote>

Credential is not required but write. 
</blockquote></details>

Done.
___
*[source/PostgreSqlDsc.psd1, line 85 at r3](https://reviewable.io/reviews/dsccommunity/postgresqldsc/5#-MKfGSZwAilqmevcTZQk:-MKfTHf40HGY4POOoTW7:b-896fix) ([raw file](https://github.com/dsccommunity/postgresqldsc/blob/acadc69eedcc26b051f12737c063fff344ad3caf/source/PostgreSqlDsc.psd1#L85)):*
<details><summary><i>Previously, jcwalker (Jason Walker) wrote…</i></summary><blockquote>

> ```
> ,
> ```
The comma isn't needed since the new resource is on a newline.
</blockquote></details>

Done.
___
*[source/DSCResources/DSC_PostgreSqlScript/DSC_PostgreSqlScript.psm1, line 25 at r2](https://reviewable.io/reviews/dsccommunity/postgresqldsc/5#-MKeYUQ97nFdA764I5Vf:-MKfTIVD7zoPfyCk_Odm:b-896fix) ([raw file](https://github.com/dsccommunity/postgresqldsc/blob/688e5fa5b0d1a43ed6504b3ebcf50c24792c3f8a/source/DSCResources/DSC_PostgreSqlScript/DSC_PostgreSqlScript.psm1#L25)):*
<details><summary><i>Previously, rchristman89 (Ryan Christman) wrote…</i></summary><blockquote>

Missing period.
</blockquote></details>

Done.
___
*[source/DSCResources/DSC_PostgreSqlScript/DSC_PostgreSqlScript.psm1, line 54 at r2](https://reviewable.io/reviews/dsccommunity/postgresqldsc/5#-MKebEqW-Bh0uG4oHiba:-MKfTPAQ5nFNF0fvH5sw:b-896fix) ([raw file](https://github.com/dsccommunity/postgresqldsc/blob/688e5fa5b0d1a43ed6504b3ebcf50c24792c3f8a/source/DSCResources/DSC_PostgreSqlScript/DSC_PostgreSqlScript.psm1#L54)):*
<details><summary><i>Previously, rchristman89 (Ryan Christman) wrote…</i></summary><blockquote>

> ```
>         [System.Management.Automation.Credential()]
> ```
This allows you to pass in a username as a string and have an interactive prompt for the password, which I’ll demonstrate later in the post. I tested this out and it does not work in DSC. This can be removed.
</blockquote></details>

Done.
___
*[source/DSCResources/DSC_PostgreSqlScript/DSC_PostgreSqlScript.psm1, line 151 at r3](https://reviewable.io/reviews/dsccommunity/postgresqldsc/5#-MKfHSFY7irHkyEG7g5l:-MKfTQeJ6xqDFYhRf1-5:b-tt9nbt) ([raw file](https://github.com/dsccommunity/postgresqldsc/blob/acadc69eedcc26b051f12737c063fff344ad3caf/source/DSCResources/DSC_PostgreSqlScript/DSC_PostgreSqlScript.psm1#L151)):*
<details><summary><i>Previously, jcwalker (Jason Walker) wrote…</i></summary><blockquote>

> ```
>         $previousErrorActionPreference = $ErrorActionPreference
>         $ErrorActionPreference = "Stop"
> ```
Why are we doing this vs adding a '-ErrorAction Stop' at the end the cmdlets?
</blockquote></details>

Something with the way we are using Invoke-Command with the psql command line tool won't catch specific errors when using -ErrorAction Stop.  If you set the EAP to stop, it does.  I can show some examples if you're interested.
___
*[source/DSCResources/DSC_PostgreSqlScript/DSC_PostgreSqlScript.psm1, line 152 at r3](https://reviewable.io/reviews/dsccommunity/postgresqldsc/5#-MKfC1mI2Z1aeg8eaPha:-MKfU8_aAutxbl4_Yy5X:b-896fix) ([raw file](https://github.com/dsccommunity/postgresqldsc/blob/acadc69eedcc26b051f12737c063fff344ad3caf/source/DSCResources/DSC_PostgreSqlScript/DSC_PostgreSqlScript.psm1#L152)):*
<details><summary><i>Previously, rchristman89 (Ryan Christman) wrote…</i></summary><blockquote>

I believe acronyms of two letters should be capitalized for camelCase. 
Same with $db below
</blockquote></details>

Done.
___
*[source/DSCResources/DSC_PostgreSqlScript/DSC_PostgreSqlScript.psm1, line 153 at r3](https://reviewable.io/reviews/dsccommunity/postgresqldsc/5#-MKfCmGE6S93bPs_PvlC:-MKfTvcQ-F1drVZZr2hx:b-896fix) ([raw file](https://github.com/dsccommunity/postgresqldsc/blob/acadc69eedcc26b051f12737c063fff344ad3caf/source/DSCResources/DSC_PostgreSqlScript/DSC_PostgreSqlScript.psm1#L153)):*
<details><summary><i>Previously, rchristman89 (Ryan Christman) wrote…</i></summary><blockquote>

I would add a verbose statement before this saying it is "Listing databases" or something similar. It helps when debugging. It may be nice to put the command being ran in the statement.
</blockquote></details>

Done.
___
*[source/DSCResources/DSC_PostgreSqlScript/DSC_PostgreSqlScript.psm1, line 166 at r3](https://reviewable.io/reviews/dsccommunity/postgresqldsc/5#-MKfCwSn7twAn30NCMi5:-MKfUFCg0y1Zapu-vJIJ:b-896fix) ([raw file](https://github.com/dsccommunity/postgresqldsc/blob/acadc69eedcc26b051f12737c063fff344ad3caf/source/DSCResources/DSC_PostgreSqlScript/DSC_PostgreSqlScript.psm1#L166)):*
<details><summary><i>Previously, rchristman89 (Ryan Christman) wrote…</i></summary><blockquote>

I would add a verbose statement before this saying it is "Creating databases" or something similar. It helps when debugging. It may be nice to put the command being ran in the statement.
</blockquote></details>

Done.
___
*[source/DSCResources/DSC_PostgreSqlScript/DSC_PostgreSqlScript.psm1, line 169 at r3](https://reviewable.io/reviews/dsccommunity/postgresqldsc/5#-MKfGy9dEusGO5FhWOlF:-MKfUGxuDPfmoED_1_-b:b-896fix) ([raw file](https://github.com/dsccommunity/postgresqldsc/blob/acadc69eedcc26b051f12737c063fff344ad3caf/source/DSCResources/DSC_PostgreSqlScript/DSC_PostgreSqlScript.psm1#L169)):*
<details><summary><i>Previously, jcwalker (Jason Walker) wrote…</i></summary><blockquote>

Style guidelines suggest a newline after a closing brace.
https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#two-newlines-after-closing-brace
</blockquote></details>

Done.
___
*[source/DSCResources/DSC_PostgreSqlScript/DSC_PostgreSqlScript.psm1, line 170 at r3](https://reviewable.io/reviews/dsccommunity/postgresqldsc/5#-MKfD-_MALiEChmlmbcv:-MKfUIcD7GCSdQi6oD1K:b-896fix) ([raw file](https://github.com/dsccommunity/postgresqldsc/blob/acadc69eedcc26b051f12737c063fff344ad3caf/source/DSCResources/DSC_PostgreSqlScript/DSC_PostgreSqlScript.psm1#L170)):*
<details><summary><i>Previously, rchristman89 (Ryan Christman) wrote…</i></summary><blockquote>

I would move the verbose statement from above to here, 
```
Write-Verbose -Message ($script:localizedData.ExecutingSetScript -f $SetFilePath,$DatabaseName)
```'
It may be nice to put the command being ran in the statement.
</blockquote></details>

Done.
___
*[source/DSCResources/DSC_PostgreSqlScript/DSC_PostgreSqlScript.psm1, line 198 at r3](https://reviewable.io/reviews/dsccommunity/postgresqldsc/5#-MKfHjED2dI1UEmnwCcj:-MKfUJajAOh1cb0c8aZ-:b-896fix) ([raw file](https://github.com/dsccommunity/postgresqldsc/blob/acadc69eedcc26b051f12737c063fff344ad3caf/source/DSCResources/DSC_PostgreSqlScript/DSC_PostgreSqlScript.psm1#L198)):*
<details><summary><i>Previously, jcwalker (Jason Walker) wrote…</i></summary><blockquote>

> ```
> `
> ```
Did we want to use backticks ( `GetResult`) or single quotes ('GetResult') to surround GetResult
</blockquote></details>

Done.
___
*[source/DSCResources/DSC_PostgreSqlScript/DSC_PostgreSqlScript.schema.mof, line 6 at r3](https://reviewable.io/reviews/dsccommunity/postgresqldsc/5#-MKfJOEk9yKHXdh1xG8b:- [...]

2020-10-27 21:29 UTC, rchristman89 approved these changes
> Reviewed 1 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/postgresqldsc/5)* status: 3 of 8 files reviewed, 6 unresolved discussions (waiting on @chtoone, @jcwalker, @jeffotterpohl, @rchristman89, and @regedit32)



<!-- Sent from Reviewable.io -->

2020-10-28 16:07 UTC, jcwalker commented
___
*[source/DSCResources/DSC_PostgreSqlScript/DSC_PostgreSqlScript.psm1, line 151 at r3](https://reviewable.io/reviews/dsccommunity/postgresqldsc/5#-MKfHSFY7irHkyEG7g5l:-MKjxgpj3y65Bn9K22V3:b306275) ([raw file](https://github.com/dsccommunity/postgresqldsc/blob/acadc69eedcc26b051f12737c063fff344ad3caf/source/DSCResources/DSC_PostgreSqlScript/DSC_PostgreSqlScript.psm1#L151)):*
<details><summary><i>Previously, themitchk wrote…</i></summary><blockquote>

Something with the way we are using Invoke-Command with the psql command line tool won't catch specific errors when using -ErrorAction Stop.  If you set the EAP to stop, it does.  I can show some examples if you're interested.
</blockquote></details>

No that's fine.


<!-- Sent from Reviewable.io -->

2020-10-28 16:08 UTC, jcwalker reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 2 of 5 files at r4, 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/postgresqldsc/5#-:-MKjxwdB5VrYNLEKbSWZ:bg7igkv)* status: 7 of 8 files reviewed, all discussions resolved (waiting on @chtoone, @jeffotterpohl, @rchristman89, and @regedit32)



<!-- Sent from Reviewable.io -->

2020-10-28 16:08 UTC, jcwalker reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/dsccommunity/postgresqldsc/5#-:-MKjy04f3xkhdbQNZufX:bnfp4nl)* status: 7 of 8 files reviewed, all discussions resolved (waiting on @chtoone, @jeffotterpohl, @rchristman89, and @regedit32)



<!-- Sent from Reviewable.io -->

2020-10-28 17:26 UTC, regedit32 reviewed
> Reviewed 1 of 7 files at r1, 2 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/postgresqldsc/5)* status: all files reviewed, 4 unresolved discussions (waiting on @chtoone, @jeffotterpohl, and @themitchk)

___
*[README.md, line 41 at r5](https://reviewable.io/reviews/dsccommunity/postgresqldsc/5#-MKkCmpkC5oD2A2poqA-:-MKkCmpkC5oD2A2poqA0:bvu0dlh) ([raw file](https://github.com/dsccommunity/postgresqldsc/blob/32eabf7dda2a9435cfea0b0ab8ef08b8f5809ea3/README.md#L41)):*
> ```
> SetFilePath 
> ```
`TestFilePath`.  I think we should also describe what the T-SQL script is expected to do in each Get/Set/Test.  For example, should the Test script return boolean, error, or null if in desired state or not.
___
*[source/DSCResources/DSC_PostgreSqlScript/DSC_PostgreSqlScript.psm1, line 76 at r5](https://reviewable.io/reviews/dsccommunity/postgresqldsc/5#-MKk9H_a2Y9miVVy2XXY:-MKk9H_bECABATZYNZ4o:b-n8xsjo) ([raw file](https://github.com/dsccommunity/postgresqldsc/blob/32eabf7dda2a9435cfea0b0ab8ef08b8f5809ea3/source/DSCResources/DSC_PostgreSqlScript/DSC_PostgreSqlScript.psm1#L76)):*
<details><summary><i alt="summary">Quoted 8 lines of code…</i></summary>

> ```
>     $returnValue = @{
>         DatabaseName     = $DatabaseName
>         SetFilePath      = $SetFilePath
>         GetFilePath      = $GetFilePath
>         TestFilePath     = $TestFilePath
>         GetResult        = [System.String[]] $getResult
>     }
>     return $returnValue
> ```
</details>

Missing the value for `CreateDatabase`.  Get-DscConfiguration will throw if the resource does not return all settings defined in the schema.mof
___
*[source/DSCResources/DSC_PostgreSqlScript/DSC_PostgreSqlScript.psm1, line 202 at r5](https://reviewable.io/reviews/dsccommunity/postgresqldsc/5#-MKkDLoY6uuUlXIbSLcG:-MKkDLoZ9ocDOvwWyRhI:bhn4l9e) ([raw file](https://github.com/dsccommunity/postgresqldsc/blob/32eabf7dda2a9435cfea0b0ab8ef08b8f5809ea3/source/DSCResources/DSC_PostgreSqlScript/DSC_PostgreSqlScript.psm1#L202)):*
> ```
> Any script that does not throw an error is evaluated to true.
> ```
I noticed in the other function help, it has a different message for this parameter and says "Any script that does not throw an error or _returns null_ is evaluated to true." I noticed we're not checking the output for null, so perhaps the other messages need to be updated.  Or alternatively, maybe we should check the result, which would match the behavior for SqlServerDsc/SqlScript resource.
___
*[tests/Unit/DSCResources/DSC_PostgreSqlScript.tests.ps1, line 57 at r5](https://reviewable.io/reviews/dsccommunity/postgresqldsc/5#-MKkAywmCqspETcZSQ9E:-MKkAywmCqspETcZSQ9F:bkm4gz2) ([raw file](https://github.com/dsccommunity/postgresqldsc/blob/32eabf7dda2a9435cfea0b0ab8ef08b8f5809ea3/tests/Unit/DSCResources/DSC_PostgreSqlScript.tests.ps1#L57)):*
> ```
> Mock Invoke-Command {return '<Script Output Sample>'}
> ```
We should use named parameters in all places.  Here we're missing `-CommandName` and `-MockWith`.  Same applies to the other mocks throughout, so I won't comment on each


<!-- Sent from Reviewable.io -->

2020-10-29 14:26 UTC, themitchk reviewed
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/postgresqldsc/5)* status: 4 of 8 files reviewed, 4 unresolved discussions (waiting on @chtoone, @jcwalker, @jeffotterpohl, @rchristman89, and @regedit32)

___
*[README.md, line 41 at r5](https://reviewable.io/reviews/dsccommunity/postgresqldsc/5#-MKkCmpkC5oD2A2poqA-:-MKojmwG6_1cN05nLHva:b-896fix) ([raw file](https://github.com/dsccommunity/postgresqldsc/blob/32eabf7dda2a9435cfea0b0ab8ef08b8f5809ea3/README.md#L41)):*
<details><summary><i>Previously, regedit32 (Reggie Gibson) wrote…</i></summary><blockquote>

> ```
> SetFilePath 
> ```
`TestFilePath`.  I think we should also describe what the T-SQL script is expected to do in each Get/Set/Test.  For example, should the Test script return boolean, error, or null if in desired state or not.
</blockquote></details>

Done.
___
*[source/DSCResources/DSC_PostgreSqlScript/DSC_PostgreSqlScript.psm1, line 76 at r5](https://reviewable.io/reviews/dsccommunity/postgresqldsc/5#-MKk9H_a2Y9miVVy2XXY:-MKojq_O8CmP1tbG9coX:b-896fix) ([raw file](https://github.com/dsccommunity/postgresqldsc/blob/32eabf7dda2a9435cfea0b0ab8ef08b8f5809ea3/source/DSCResources/DSC_PostgreSqlScript/DSC_PostgreSqlScript.psm1#L76)):*
<details><summary><i>Previously, regedit32 (Reggie Gibson) wrote…</i></summary><blockquote>

> ```
>     $returnValue = @{
>         DatabaseName     = $DatabaseName
>         SetFilePath      = $SetFilePath
>         GetFilePath      = $GetFilePath
>         TestFilePath     = $TestFilePath
>         GetResult        = [System.String[]] $getResult
>     }
>     return $returnValue
> ```
Missing the value for `CreateDatabase`.  Get-DscConfiguration will throw if the resource does not return all settings defined in the schema.mof
</blockquote></details>

Done.
___
*[source/DSCResources/DSC_PostgreSqlScript/DSC_PostgreSqlScript.psm1, line 202 at r5](https://reviewable.io/reviews/dsccommunity/postgresqldsc/5#-MKkDLoY6uuUlXIbSLcG:-MKojrXLAajoAA2Cdq8w:b4gng92) ([raw file](https://github.com/dsccommunity/postgresqldsc/blob/32eabf7dda2a9435cfea0b0ab8ef08b8f5809ea3/source/DSCResources/DSC_PostgreSqlScript/DSC_PostgreSqlScript.psm1#L202)):*
<details><summary><i>Previously, regedit32 (Reggie Gibson) wrote…</i></summary><blockquote>

> ```
> Any script that does not throw an error is evaluated to true.
> ```
I noticed in the other function help, it has a different message for this parameter and says "Any script that does not throw an error or _returns null_ is evaluated to true." I noticed we're not checking the output for null, so perhaps the other messages need to be updated.  Or alternatively, maybe we should check the result, which would match the behavior for SqlServerDsc/SqlScript resource.
</blockquote></details>

Good catch.  Updated help text, as psql returns weird things and it's not trivial to parse a boolean out.  If we need to adjust this later based on feedback we can
___
*[tests/Unit/DSCResources/DSC_PostgreSqlScript.tests.ps1, line 57 at r5](https://reviewable.io/reviews/dsccommunity/postgresqldsc/5#-MKkAywmCqspETcZSQ9E:-MKok2PUAvucgCSyUYRG:b-896fix) ([raw file](https://github.com/dsccommunity/postgresqldsc/blob/32eabf7dda2a9435cfea0b0ab8ef08b8f5809ea3/tests/Unit/DSCResources/DSC_PostgreSqlScript.tests.ps1#L57)):*
<details><summary><i>Previously, regedit32 (Reggie Gibson) wrote…</i></summary><blockquote>

> ```
> Mock Invoke-Command {return '<Script Output Sample>'}
> ```
We should use named parameters in all places.  Here we're missing `-CommandName` and `-MockWith`.  Same applies to the other mocks throughout, so I won't comment on each
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-10-29 14:26 UTC, themitchk reviewed
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/postgresqldsc/5)* status: 4 of 8 files reviewed, 4 unresolved discussions (waiting on @chtoone, @jcwalker, @jeffotterpohl, @rchristman89, and @regedit32)

___
*[source/DSCResources/DSC_PostgreSqlScript/DSC_PostgreSqlScript.psm1, line 202 at r5](https://reviewable.io/reviews/dsccommunity/postgresqldsc/5#-MKkDLoY6uuUlXIbSLcG:-MKok7jGBYfMbtBFcmka:b-896fix) ([raw file](https://github.com/dsccommunity/postgresqldsc/blob/32eabf7dda2a9435cfea0b0ab8ef08b8f5809ea3/source/DSCResources/DSC_PostgreSqlScript/DSC_PostgreSqlScript.psm1#L202)):*
<details><summary><i>Previously, themitchk wrote…</i></summary><blockquote>

Good catch.  Updated help text, as psql returns weird things and it's not trivial to parse a boolean out.  If we need to adjust this later based on feedback we can
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-10-29 14:45 UTC, merged